### PR TITLE
Working test runner without docker files

### PR DESCRIPTION
**Pull request by loziniak**

### CODE REVIEW

**Comment by iHiD** [comment]
That was fast! Nice work :) If you don't know Docker and want someone to wrap this for you, @ErikSchierboom can do it next week.

**Review by ErikSchierboom — APPROVED** [review]
Do you need any help with the Docker part?

**Comment by loziniak** [comment]
Thanks!

> That was fast!

@iHiD It's always like that with Red :-D

> Do you need any help with the Docker part?

@ErikSchierboom I have very little experience with Docker and I don't use it on a daily basis. So, If it wouldn't be too much, I'd happily let someone else do that.

What would you need from me? Probably a script to install Red?

Would it be also possible to do some CI and run `test-runner-test.red` on each commit/PR? I totally don't know Github Actions.

**Comment by ErikSchierboom** [comment]
> What would you need from me? Probably a script to install Red?

Yes. The script should preferrably work on either Alpine or Ubuntu.

> Would it be also possible to do some CI and run test-runner-test.red on each commit/PR? I totally don't know Github Actions.

Yes, this is certainly possible. I can also help with that.

**Pull request merged**
